---
abstract: 'Perl interface to the cairo 2d vector graphics library'
author:
  - 'Cairo Perl Team <gtk-perl-list at gnome dot org>'
build_requires: {}
configure_requires:
  ExtUtils::Depends: 0.2
  ExtUtils::PkgConfig: 1
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Cairo
no_index:
  directory:
    - t
    - inc
  file:
    - inc/MakeHelper.pm
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Cairo
  homepage: http://gtk2-perl.sourceforge.net
  license: http://www.gnu.org/licenses/lgpl-2.1.html
  repository: git://git.gnome.org/perl-Cairo
  x_MailingList: https://mail.gnome.org/mailman/listinfo/gtk-perl-list
version: 1.102
