--- #YAML:1.0
name:               Cairo
version:            1.082
abstract:           Perl interface to the cairo 2d vector graphics library
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::Depends:    0.2
    ExtUtils::MakeMaker:  0
    ExtUtils::PkgConfig:  1
build_requires:
    ExtUtils::MakeMaker:  0
    Test::Number::Delta:  1
requires:
    ExtUtils::Depends:    0.2
    ExtUtils::PkgConfig:  1
no_index:
    directory:
        - t
        - inc
    files:
        - inc/MakeHelper.pm
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
