# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Cairo
version:      0.92
version_from: Cairo.pm
installdirs:  site
requires:
    ExtUtils::Depends:             0.2
    ExtUtils::PkgConfig:           1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
